package objects

import "github.com/rajnikant12345/kmip_g/kmipbin"

type MapValue struct {
	Val string
	F   func() interface{}
}

func intVal() interface{} {
	return new(kmipbin.KmipInt)
}

func longIntVal() interface{} {
	return new(kmipbin.KmipLongInt)
}

func bigIntVal() interface{} {
	return new(kmipbin.KmipBigInt)
}

func enumVal() interface{} {
	return new(kmipbin.KmipEnum)
}

func boolVal() interface{} {
	return new(kmipbin.KmipBoolean)
}

func textStringVal() interface{} {
	return new(kmipbin.KmipTextString)
}

func byteStringVal() interface{} {
	return new(kmipbin.KmipByteString)
}

func dateVal() interface{} {
	return new(kmipbin.KmipDate)
}

func intervalVal() interface{} {
	return new(kmipbin.KmipInterval)
}

var TagsNew = map[string]MapValue{
	"None":                                  {"000000", nil},
	"ActivationDate":                        {"420001", dateVal},
	"ApplicationData":                       {"420002", textStringVal},
	"ApplicationNamespace":                  {"420003", textStringVal},
	"ApplicationSpecificInformation":        {"420004", func() interface{}{return new(ApplicationSpecificInformation)}},
	"ArchiveDate":                           {"420005", dateVal},
	"AsynchronousCorrelationValue":          {"420006", byteStringVal},
	"AsynchronousIndicator":                 {"420007", boolVal},
	"Attribute":                             {"420008", func() interface{}{return new(Attribute)} },
	"AttributeIndex":                        {"420009", intVal},
	"AttributeName":                         {"42000A", textStringVal},
	"AttributeValue":                        {"42000B", nil},
	"Authentication":                        {"42000C", nil},
	"BatchCount":                            {"42000D", intVal},
	"BatchErrorContinuationOption":          {"42000E", enumVal},
	"BatchItem":                             {"42000F", func() interface{}{return new(BatchItem)}},
	"BatchOrderOption":                      {"420010", boolVal},
	"BlockCipherMode":                       {"420011", enumVal},
	"CancellationResult":                    {"420012", enumVal},
	"Certificate":                           {"420013", func() interface{}{return new(Certificate)}},
	"CertificateIdentifier":                 {"420014", func() interface{}{return new(CertificateIdentifier)}},
	"CertificateIssuer":                     {"420015", func() interface{}{return new(CertificateIssuer)}},
	"CertificateIssuerAlternativeName":      {"420016", textStringVal},
	"CertificateIssuerDistinguishedName":    {"420017", textStringVal},
	"CertificateRequest":                    {"420018", byteStringVal},
	"CertificateRequestType":                {"420019", enumVal},
	"CertificateSubject":                    {"42001A", func() interface{}{return new(CertificateSubject)}},
	"CertificateSubjectAlternativeName":     {"42001B", textStringVal},
	"CertificateSubjectDistinguishedName":   {"42001C", textStringVal},
	"CertificateType":                       {"42001D", enumVal},
	"CertificateValue":                      {"42001E", byteStringVal},
	"CommonTemplateAttribute":               {"42001F", func() interface{}{return new(CommonTemplateAttribute)}},
	"CompromiseDate":                        {"420020", dateVal},
	"CompromiseOccurrenceDate":              {"420021", dateVal},
	"ContactInformation":                    {"420022", textStringVal},
	"Credential":                            {"420023", func() interface{}{return new(Credential)}},
	"CredentialType":                        {"420024", enumVal},
	"CredentialValue":                       {"420025", func() interface{}{return new(CredentialValue)}},
	"CriticalityIndicator":                  {"420026", boolVal},
	"CRTCoefficient":                        {"420027", bigIntVal},
	"CryptographicAlgorithm":                {"420028", enumVal},
	"CryptographicDomainParameters":         {"420029", func() interface{}{return new(CryptographicDomainParameters)}},
	"CryptographicLength":                   {"42002A", intVal},
	"CryptographicParameters":               {"42002B", func() interface{}{return new(CryptographicParameters)}},
	"CryptographicUsageMask":                {"42002C", intVal},
	"CustomAttribute":                       {"42002D", nil},
	"D":                                     {"42002E", bigIntVal},
	"DeactivationDate":                      {"42002F", dateVal},
	"DerivationData":                        {"420030", byteStringVal},
	"DerivationMethod":                      {"420031", enumVal},
	"DerivationParameters":                  {"420032", func() interface{}{return new(DerivationParameters)}},
	"DestroyDate":                           {"420033", dateVal},
	"Digest":                                {"420034", func() interface{}{return new(Digest)}},
	"DigestValue":                           {"420035", byteStringVal},
	"EncryptionKeyInformation":              {"420036", func() interface{}{return new(EncryptionKeyInformation)}},
	"G":                                     {"420037", bigIntVal},
	"HashingAlgorithm":                      {"420038", enumVal},
	"InitialDate":                           {"420039", dateVal},
	"InitializationVector":                  {"42003A", byteStringVal},
	"Issuer":                                {"42003B", textStringVal},
	"IterationCount":                        {"42003C", intVal},
	"IV/Counter/Nonce":                      {"42003D", byteStringVal},
	"J":                                     {"42003E", bigIntVal},
	"Key":                                   {"42003F", byteStringVal},
	"KeyBlock":                              {"420040", func() interface{}{return new(KeyBlock)}},
	"KeyCompressionType":                    {"420041", enumVal},
	"KeyFormatType":                         {"420042", enumVal},
	"KeyMaterial":                           {"420043", nil},
	"KeyPartIdentifier":                     {"420044", intVal},
	"KeyValue":                              {"420045", func() interface{}{return new(KeyValue)}},
	"KeyWrappingData":                       {"420046", func() interface{}{return new(KeyWrappingData)}},
	"KeyWrappingSpecification":              {"420047", func() interface{}{return new(KeyWrappingSpecification)}},
	"LastChangeDate":                        {"420048", dateVal},
	"LeaseTime":                             {"420049", intervalVal},
	"Link":                                  {"42004A", func() interface{}{return new(Link)}},
	"LinkType":                              {"42004B", enumVal},
	"LinkedObjectIdentifier":                {"42004C", textStringVal},
	"MACSignature":                          {"42004D", byteStringVal},
	"MACSignatureKeyInformation":            {"42004E", func() interface{}{return new(MACSignatureKeyInformation)}},
	"MaximumItems":                          {"42004F", intVal},
	"MaximumResponseSize":                   {"420050", intVal},
	"MessageExtension":                      {"420051", func() interface{}{return new(MessageExtension)}},
	"Modulus":                               {"420052", bigIntVal},
	"Name":                                  {"420053", func() interface{}{return new(Name)}},
	"NameType":                              {"420054", enumVal},
	"NameValue":                             {"420055", textStringVal},
	"ObjectGroup":                           {"420056", textStringVal},
	"ObjectType":                            {"420057", enumVal},
	"Offset":                                {"420058", intervalVal},
	"OpaqueDataType":                        {"420059", enumVal},
	"OpaqueDataValue":                       {"42005A", byteStringVal},
	"OpaqueObject":                          {"42005B", func() interface{}{return new(OpaqueObject)}},
	"Operation":                             {"42005C", enumVal},
	"OperationPolicyName":                   {"42005D", textStringVal},
	"P":                                     {"42005E", bigIntVal},
	"PaddingMethod":                         {"42005F", enumVal},
	"PrimeExponentP":                        {"420060", bigIntVal},
	"PrimeExponentQ":                        {"420061", bigIntVal},
	"PrimeFieldSize":                        {"420062", bigIntVal},
	"PrivateExponent":                       {"420063", bigIntVal},
	"PrivateKey":                            {"420064", func() interface{}{return new(PrivateKey)}},
	"PrivateKeyTemplateAttribute":           {"420065", func() interface{}{return new(PrivateKeyTemplateAttribute)}},
	"PrivateKeyUniqueIdentifier":            {"420066", textStringVal},
	"ProcessStartDate":                      {"420067", dateVal},
	"ProtectStopDate":                       {"420068", dateVal},
	"ProtocolVersion":                       {"420069", func() interface{}{return new(ProtocolVersion)}},
	"ProtocolVersionMajor":                  {"42006A", intVal},
	"ProtocolVersionMinor":                  {"42006B", intVal},
	"PublicExponent":                        {"42006C", bigIntVal},
	"PublicKey":                             {"42006D", func() interface{}{return new(PublicKey)}},
	"PublicKeyTemplateAttribute":            {"42006E", func() interface{}{return new(PublicKeyTemplateAttribute)}},
	"PublicKeyUniqueIdentifier":             {"42006F", textStringVal},
	"PutFunction":                           {"420070", enumVal},
	"Q":                                     {"420071", bigIntVal},
	"QString":                               {"420072", byteStringVal},
	"Qlength":                               {"420073", intVal},
	"QueryFunction":                         {"420074", enumVal},
	"RecommendedCurve":                      {"420075", enumVal},
	"ReplacedUniqueIdentifier":              {"420076", textStringVal},
	"RequestHeader":                         {"420077", func() interface{}{return new(RequestHeader)}},
	"RequestMessage":                        {"420078", func() interface{}{return new(RequestMessage)}},
	"RequestPayload":                        {"420079", func() interface{}{return new(RequestPayload)}},
	"ResponseHeader":                        {"42007A", func() interface{}{return new(ResponseHeader)}},
	"ResponseMessage":                       {"42007B", func() interface{}{return new(ResponseMessage)}},
	"ResponsePayload":                       {"42007C", func() interface{}{return new(ResponsePayload)}},
	"ResultMessage":                         {"42007D", textStringVal},
	"ResultReason":                          {"42007E", enumVal},
	"ResultStatus":                          {"42007F", enumVal},
	"RevocationMessage":                     {"420080", textStringVal},
	"RevocationReason":                      {"420081", func() interface{}{return new(RevocationReason)}},
	"RevocationReasonCode":                  {"420082", enumVal},
	"KeyRoleType":                           {"420083", nil},
	"Salt":                                  {"420084", byteStringVal},
	"SecretData":                            {"420085", func() interface{}{return new(SecretData)}},
	"SecretDataType":                        {"420086", enumVal},
	"SerialNumber":                          {"420087", textStringVal},
	"ServerInformation":                     {"420088", nil},
	"SplitKey":                              {"420089", func() interface{}{return new(SplitKey)}},
	"SplitKeyMethod":                        {"42008A", enumVal},
	"SplitKeyParts":                         {"42008B", intVal},
	"SplitKeyThreshold":                     {"42008C", intVal},
	"State":                                 {"42008D", enumVal},
	"StorageStatusMask":                     {"42008E", intVal},
	"SymmetricKey":                          {"42008F", func() interface{}{return new(SymmetricKey)}},
	"Template":                              {"420090", func() interface{}{return new(Template)}},
	"TemplateAttribute":                     {"420091", func() interface{}{return new(TemplateAttribute)}},
	"TimeStamp":                             {"420092", dateVal},
	"UniqueBatchItemID":                     {"420093", byteStringVal},
	"UniqueIdentifier":                      {"420094", textStringVal},
	"UsageLimits":                           {"420095", func() interface{}{return new(UsageLimits)}},
	"UsageLimitsCount":                      {"420096", longIntVal},
	"UsageLimitsTotal":                      {"420097", longIntVal},
	"UsageLimitsUnit":                       {"420098", enumVal},
	"Username":                              {"420099", textStringVal},
	"ValidityDate":                          {"42009A", dateVal},
	"ValidityIndicator":                     {"42009B", enumVal},
	"VendorExtension":                       {"42009C", nil},
	"VendorIdentification":                  {"42009D", textStringVal},
	"WrappingMethod":                        {"42009E", enumVal},
	"X":                                     {"42009F", bigIntVal},
	"Y":                                     {"4200A0", bigIntVal},
	"Password":                              {"4200A1", textStringVal},
	"DeviceIdentifier":                      {"4200A2", textStringVal},
	"EncodingOption":                        {"4200A3", enumVal},
	"ExtensionInformation":                  {"4200A4", func() interface{}{return new(ExtensionInformation)}},
	"ExtensionName":                         {"4200A5", textStringVal},
	"ExtensionTag":                          {"4200A6", intVal},
	"ExtensionType":                         {"4200A7", intVal},
	"Fresh":                                 {"4200A8", boolVal},
	"MachineIdentifier":                     {"4200A9", textStringVal},
	"MediaIdentifier":                       {"4200AA", textStringVal},
	"NetworkIdentifier":                     {"4200AB", textStringVal},
	"ObjectGroupMember":                     {"4200AC", enumVal},
	"CertificateLength":                     {"4200AD", intVal},
	"DigitalSignatureAlgorithm":             {"4200AE", enumVal},
	"CertificateSerialNumber":               {"4200AF", byteStringVal},
	"DeviceSerialNumber":                    {"4200B0", textStringVal},
	"IssuerAlternativeName":                 {"4200B1", byteStringVal},
	"IssuerDistinguishedName":               {"4200B2", byteStringVal},
	"SubjectAlternativeName":                {"4200B3", byteStringVal},
	"SubjectDistinguishedName":              {"4200B4", byteStringVal},
	"X509CertificateIdentifier":             {"4200B5", func() interface{}{return new(X509CertificateIdentifier)}},
	"X509CertificateIssuer":                 {"4200B6", func() interface{}{return new(X509CertificateIssuer)}},
	"X509CertificateSubject":                {"4200B7", func() interface{}{return new(X509CertificateSubject)}},
	"KeyValueLocation":                      {"4200B8", func() interface{}{return new(KeyValueLocation)}},
	"KeyValueLocationValue":                 {"4200B9", textStringVal},
	"KeyValueLocationType":                  {"4200BA", enumVal},
	"KeyValuePresent":                       {"4200BB", boolVal},
	"OriginalCreationDate":                  {"4200BC", dateVal},
	"PGPKey":                                {"4200BD", func() interface{}{return new(PGPKey)}},
	"PGPKeyVersion":                         {"4200BE", intVal},
	"AlternativeName":                       {"4200BF", nil},
	"AlternativeNameValue":                  {"4200C0", nil},
	"AlternativeNameType":                   {"4200C1", nil},
	"Data":                                  {"4200C2", nil},
	"SignatureData":                         {"4200C3", nil},
	"DataLength":                            {"4200C4", nil},
	"RandomIV":                              {"4200C5", nil},
	"MACData":                               {"4200C6", nil},
	"AttestationType":                       {"4200C7", nil},
	"Nonce":                                 {"4200C8", nil},
	"NonceID":                               {"4200C9", nil},
	"NonceValue":                            {"4200CA", nil},
	"AttestationMeasurement":                {"4200CB", nil},
	"AttestationAssertion":                  {"4200CC", nil},
	"IVLength":                              {"4200CD", nil},
	"TagLength":                             {"4200CE", nil},
	"FixedFieldLength":                      {"4200CF", nil},
	"CounterLength":                         {"4200D0", nil},
	"InitialCounterValue":                   {"4200D1", nil},
	"InvocationFieldLength":                 {"4200D2", nil},
	"AttestationCapableIndicator":           {"4200D3", nil},
	"OffsetItems":                           {"4200D4", nil},
	"LocatedItems":                          {"4200D5", nil},
	"CorrelationValue":                      {"4200D6", nil},
	"InitIndicator":                         {"4200D7", nil},
	"FinalIndicator":                        {"4200D8", nil},
	"RNGParameters":                         {"4200D9", nil},
	"RNGAlgorithm":                          {"4200DA", nil},
	"DRBGAlgorithm":                         {"4200DB", nil},
	"FIPS186Variation":                      {"4200DC", nil},
	"PredictionResistance":                  {"4200DD", nil},
	"RandomNumberGenerator":                 {"4200DE", nil},
	"ValidationInformation":                 {"4200DF", nil},
	"ValidationAuthorityType":               {"4200E0", nil},
	"ValidationAuthorityCountry":            {"4200E1", nil},
	"ValidationAuthorityURI":                {"4200E2", nil},
	"ValidationVersionMajor":                {"4200E3", nil},
	"ValidationVersionMinor":                {"4200E4", nil},
	"ValidationType":                        {"4200E5", nil},
	"ValidationLevel":                       {"4200E6", nil},
	"ValidationCertificateIdentifier":       {"4200E7", nil},
	"ValidationCertificateURI":              {"4200E8", nil},
	"ValidationVendorURI":                   {"4200E9", nil},
	"ValidationProfile":                     {"4200EA", nil},
	"ProfileInformation":                    {"4200EB", nil},
	"ProfileName":                           {"4200EC", nil},
	"ServerURI":                             {"4200ED", nil},
	"ServerPort":                            {"4200EE", nil},
	"StreamingCapability":                   {"4200EF", nil},
	"AsynchronousCapability":                {"4200F0", nil},
	"AttestationCapability":                 {"4200F1", nil},
	"UnwrapMode":                            {"4200F2", nil},
	"DestroyAction":                         {"4200F3", nil},
	"ShreddingAlgorithm":                    {"4200F4", nil},
	"RNGMode":                               {"4200F5", nil},
	"ClientRegistrationMethod":              {"4200F6", nil},
	"CapabilityInformation":                 {"4200F7", nil},
	"KeyWrapType":                           {"4200F8", nil},
	"BatchUndoCapability":                   {"4200F9", nil},
	"BatchContinueCapability":               {"4200FA", nil},
	"PKCS#12FriendlyName":                   {"4200FB", nil},
	"Description":                           {"4200FC", nil},
	"Comment":                               {"4200FD", nil},
	"AuthenticatedEncryptionAdditionalData": {"4200FE", nil},
	"AuthenticatedEncryptionTag":            {"4200FF", nil},
	"SaltLength":                            {"420100", nil},
	"MaskGenerator":                         {"420101", nil},
	"MaskGeneratorHashingAlgorithm":         {"420102", nil},
	"PSource":                               {"420103", nil},
	"TrailerField":                          {"420104", nil},
	"ClientCorrelationValue":                {"420105", nil},
	"ServerCorrelationValue":                {"420106", nil},
	"DigestedData":                          {"420107", nil},
	"CertificateSubjectCN":                  {"420108", nil},
	"CertificateSubjectO":                   {"420109", nil},
	"CertificateSubjectOU":                  {"42010A", nil},
	"CertificateSubjectEmail":               {"42010B", nil},
	"CertificateSubjectC":                   {"42010C", nil},
	"CertificateSubjectST":                  {"42010D", nil},
	"CertificateSubjectL":                   {"42010E", nil},
	"CertificateSubjectUID":                 {"42010F", nil},
	"CertificateSubjectSerialNumber":        {"420110", nil},
	"CertificateSubjectTitle":               {"420111", nil},
	"CertificateSubjectDC":                  {"420112", nil},
	"CertificateSubjectDNQualifier":         {"420113", nil},
	"CertificateIssuerCN":                   {"420114", nil},
	"CertificateIssuerO":                    {"420115", nil},
	"CertificateIssuerOU":                   {"420116", nil},
	"CertificateIssuerEmail":                {"420117", nil},
	"CertificateIssuerC":                    {"420118", nil},
	"CertificateIssuerST":                   {"420119", nil},
	"CertificateIssuerL":                    {"42011A", nil},
	"CertificateIssuerUID":                  {"42011B", nil},
	"CertificateIssuerSerialNumber":         {"42011C", nil},
	"CertificateIssuerTitle":                {"42011D", nil},
	"CertificateIssuerDC":                   {"42011E", nil},
	"CertificateIssuerDNQualifier":          {"42011F", nil},
	"Sensitive":                             {"420120", nil},
	"AlwaysSensitive":                       {"420121", nil},
	"Extractable":                           {"420122", nil},
	"NeverExtractable":                      {"420123", nil},
	"ReplaceExisting":                       {"420124", nil},
}
